#action.yaml
name: Send email on failure
description: for sending failure email
author: KKumari
branding:
  icon: 'activity'
  color: 'yellow'
runs: 
  uses: 'actions/setup-python@v2'
  run: python unsuccessful.py
